### PR TITLE
Add simple CI

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Review by jkernech — APPROVED** [review]

**Comment by CAMOBAP** [comment]
@jkernech @mrister could you please help me to test this configuration and enable this project on `CircleCI` side

**Comment by mrister** [comment]
@CAMOBAP795  sure I'm on it, what is the proper test command to run tests if there are any ?

**Review by mrister — APPROVED** [review]

**Comment by CAMOBAP** [comment]
@mrister for now there is no tests but `make build` will 
 - automatically create sample project 
 - integrate `cordova-plugin-dialonce` in it
 - and build

I think it's better then nothing for now

**Comment by mrister** [comment]
ok, sure

**Comment by mrister** [comment]
@CAMOBAP795  added

**Comment by mrister** [comment]
@CAMOBAP795  I think you should do PR to develop, not master

**Comment by CAMOBAP** [comment]
@jkernech I haven't permissions to merge this PR could you please give me permission, or merge it

**Comment by mrister** [comment]
@CAMOBAP795  I'll give it tot you.

**Comment by mrister** [comment]
@CAMOBAP795 try now please

**Comment by CAMOBAP** [comment]
@mrister  good catch I will change destination to `develop`

**Pull request merged**
